/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as guestSignupRouteImport } from './routes/(guest)/signup'
import { Route as guestLoginRouteImport } from './routes/(guest)/login'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/(app)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const guestSignupRoute = guestSignupRouteImport.update({
  id: '/(guest)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const guestLoginRoute = guestLoginRouteImport.update({
  id: '/(guest)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/login': typeof guestLoginRoute
  '/signup': typeof guestSignupRoute
  '/': typeof appIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof guestLoginRoute
  '/signup': typeof guestSignupRoute
  '/': typeof appIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/about': typeof AboutRoute
  '/(guest)/login': typeof guestLoginRoute
  '/(guest)/signup': typeof guestSignupRoute
  '/(app)/': typeof appIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/login' | '/signup' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/login' | '/signup' | '/'
  id: '__root__' | '/about' | '/(guest)/login' | '/(guest)/signup' | '/(app)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  guestLoginRoute: typeof guestLoginRoute
  guestSignupRoute: typeof guestSignupRoute
  appIndexRoute: typeof appIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guest)/signup': {
      id: '/(guest)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof guestSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guest)/login': {
      id: '/(guest)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof guestLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  guestLoginRoute: guestLoginRoute,
  guestSignupRoute: guestSignupRoute,
  appIndexRoute: appIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
